config/routes.rb
Rails.application.routes.draw do
  get '/apply', to: 'enrolment_requests#new'
  post '/apply', to: 'enrolment_requests#create'

  resources :enrolment_requests, only: [:show]

  namespace :admin do
    resources :enrolment_requests, only: [:index, :show] do
      patch 'accept', on: :member
      post 'confirm', on: :member
    end
  end
end

app/models/api_token.rb
class ApiToken
  def create
    JWT.encode(
      {
        iss: Rails.configuration.consumer_key,
        iat: Time.now.to_i
      },
      Rails.configuration.shared_secret,
      'HS256'
    )
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrolment_request.rb
class EnrolmentRequest < ApplicationRecord
  Learner = Struct.new(:first_name, :last_name, :email)
  Degree = Struct.new(:title, :code)

  def new?
    status == 'new'
  end

  def accept!
    set_status('accepted')
  end

  def submit!
    set_status('submitted')
  end

  def degree
    @degree ||=  begin
      api_token = ApiToken.new.create
      connection = Faraday.new(url: Rails.configuration.api_base_endpoint)
      connection.authorization(:Bearer, api_token)

      response = connection.get('/partners/degrees/' + degree_uuid)
      json = JSON.parse(response.body)

      Degree.new(json['title'], json['code'])
    end
  end

  def learner
    @learner ||= begin
      api_token = ApiToken.new.create
      connection = Faraday.new(url: Rails.configuration.api_base_endpoint)
      connection.authorization(:Bearer, api_token)

      response = connection.get('/partners/learners/' + learner_uuid)
      json = JSON.parse(response.body)

      Learner.new(json['first_name'], json['last_name'], json['email'])
    end
  end

  private

  def set_status(status)
    api_token = ApiToken.new.create
    connection = Faraday.new(url: Rails.configuration.api_base_endpoint)
    connection.authorization(:Bearer, api_token)

    response = connection.patch('/partners/enrolment_requests/' + uuid, status: status)

    update!(status: status)
  end
end

app/controllers/admin/enrolment_requests_controller.rb
class Admin::EnrolmentRequestsController < ApplicationController
  before_action :find_enrolment_request, only: [:accept, :confirm, :show]

  def index
    @enrolment_requests = EnrolmentRequest.all
  end

  def accept
    @enrolment_request.accept!
    flash[:notice] = 'Enrolment request successfully accepted!'
    redirect_to admin_enrolment_requests_path
  end

  def confirm
    organisation_membership_uuid = create_organisation_membership

    degree_enrolment_uuid = confirm_enrolment_request(organisation_membership_uuid)

    program_run_uuid = find_program_run_uuid

    create_program_enrolments(organisation_membership_uuid, program_run_uuid, degree_enrolment_uuid)

    @enrolment_request.update!(status: 'confirmed')

    flash[:notice] = 'Enrolment request successfully confirmed!'
    redirect_to admin_enrolment_requests_path
  end

  private

  def find_enrolment_request
    @enrolment_request = EnrolmentRequest.find(params[:id])
  end

  def create_organisation_membership
    external_learner_id = params[:external_learner_id]

    api_token = ApiToken.new.create
    connection = Faraday.new(url: Rails.configuration.api_base_endpoint)
    connection.authorization(:Bearer, api_token)

    response = connection.post('/partners/organisation_memberships', {
      external_learner_id: external_learner_id,
      learner: {
        uuid: learner_uuid
      }
    })

    json = JSON.parse(response.body)
    json['uuid']
  end

  def confirm_enrolment_request(organisation_membership_uuid)
    api_token = ApiToken.new.create
    connection = Faraday.new(url: Rails.configuration.api_base_endpoint)
    connection.authorization(:Bearer, api_token)

    response = connection.patch('/partners/enrolment_requests/' + uuid, {
      organisation_membership: {
        uuid: organisation_membership_uuid,
      },
      status: 'confirmed'
    })

    json = JSON.parse(response.body)
    json['degree_enrolment']['uuid']
  end

  def create_program_enrolments(organisation_membership_uuid, program_run_uuid, degree_enrolment_uuid)
    api_token = ApiToken.new.create
    connection = Faraday.new(url: Rails.configuration.api_base_endpoint)
    connection.authorization(:Bearer, api_token)

    response = connection.post('/partners/program_enrolments', {
      organisation_membership: {
        uuid: organisation_membership_uuid,
      },
      program_run: {
        uuid: program_run_uuid
      },
      degree_enrolment: {
        uuid: degree_enrolment_uuid
      }
    })

    debugger
  end

  def find_program_run_uuid
    api_token = ApiToken.new.create
    connection = Faraday.new(url: Rails.configuration.api_base_endpoint)
    connection.authorization(:Bearer, api_token)

    response = connection.get('/partners/program_runs/find', program_code: params[:program_code], program_run_code: params[:program_run_code])

    json = JSON.parse(response.body)
    json['uuid']
  end

  def uuid
    @enrolment_request.uuid
  end

  def learner_uuid
    @enrolment_request.learner_uuid
  end

  # attr_reader :enrolment_request

  # delegate :uuid, :learner_uuid, to: :enrolment_request
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/enrolment_requests_controller.rb
class EnrolmentRequestsController < ApplicationController
  def new
    @enrolment_request = EnrolmentRequestService.new.find_by_token(params[:token])
  end

  def create
    enrolment_request = EnrolmentRequestService.new.find_by_token(params[:token])
    enrolment_request.accept!
    redirect_to enrolment_request.return_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/enrolment_requests/index.html.erb
<table>
  <tr>
    <td>ID</td>
    <td>Learner</td>
    <td>Status</td>
    <td>Degree</td>
    <td>Actions</td>
  </tr>
  <% @enrolment_requests.each do |enrolment_request| %>
  <tr>
    <td>
      <%= enrolment_request.id %>
    </td>
    <td>
      <%= "#{enrolment_request.learner.first_name} #{enrolment_request.learner.last_name}" %>
    </td>
    <td>
      <%= enrolment_request.status %>
    </td>
    <td>
      <%= enrolment_request.degree.title %>
    </td>
    <td>
      <%= link_to 'Confirm', admin_enrolment_request_path(enrolment_request) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/enrolment_requests/show.html.erb
<h1>Confirm enrolment request</h1>
<%= form_tag confirm_admin_enrolment_request_path(@enrolment_request) do %>
  <%= label_tag :external_learner_id, 'Student ID' %>
  <%= text_field_tag :external_learner_id %>

  <%= label_tag :program_code %>
  <%= text_field_tag :program_code %>

  <%= label_tag :program_run_code %>
  <%= text_field_tag :program_run_code %>

  <%= submit_tag 'Confirm' %>
<% end %>

app/views/enrolment_requests/new.html.erb
<h1>University application form</h1>

<div>
  <p>You are applying to enrol on <%= @enrolment_request.degree.title %> (<%= @enrolment_request.degree.code %>)</p>
  <%= form_tag do %>
    <%= label_tag :first_name %>
    <%= text_field_tag :first_name, @enrolment_request.learner.first_name %>

    <%= label_tag :last_name %>
    <%= text_field_tag :last_name, @enrolment_request.learner.last_name %>

    <%= label_tag :email %>
    <%= text_field_tag :email, @enrolment_request.learner.email %>
    <%= hidden_field_tag :token, @enrolment_request.token %>
    <%= submit_tag 'Apply' %>
  <% end %>
</div>

app/views/enrolment_requests/show.html.erb
<h1>Application submitted!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlFirstEnrolmentSample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class='notice' style='background-color: green; color: white;'>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>